### PR TITLE
Fix dupe text bug

### LINKED ISSUE #14: Duplicate text and formatting issues when using formatted instances of the same word on one line.
Hi @kadikraman, we're noticing a bug where when you use multiple (at least 2) instances of the same word on a single line, and if one of those instances is formatted using bold, italics, or bold & italics, you will see duplicatation of text and some formatting issues - https://cl.ly/iOSO. 

To reproduce this: 
- Type in the following into an editor: `First bold is fine, second bold will cause issues.` (Make one of the bold instances **BOLD**
- This should result in the following output: `First bold is fine, second bold is fine, second **bold will cause issues.`

Please let me know if I can follow up with more details. 
Thanks.

### PR DESCRIPTION
**Pull request by rickhanlonii**
## Overview

This PR fixes a bug where duplicate text was being inserted when converting from draftjs to markdown.

Closes #14

### CODE REVIEW

File: src/draftjsToMd.js [hunk 1]
```diff
@@ -76,21 +76,24 @@ function fixWhitespacesInsideStyle(text, style) {
...
   // Trimmed text between markers
-  const bodyT = body.trim();
+  const bodyTrimmed = body.trim();
   // Text after closing marker
   const post = text.slice(style.range.end);
 
+  const bodyTrimmedStart = style.range.start + body.indexOf(bodyTrimmed);
+
   // Text between opening marker and trimmed content (leading spaces)
-  const prefix = text.slice(style.range.start, text.indexOf(bodyT));
```
Comment (rickhanlonii) [inline src/draftjsToMd.js]: The bug was on this line, it would match outside the trimmed content so that it finds the first "is" in:

`this __is__ a test`

rather than the one being styled

File: test/draftjsToMd.test.js [hunk 2]
```diff
@@ -497,6 +497,26 @@ describe('draftjsToMd', () => {
     draftjsToMd(raw).should.equal(expectedMarkdown);
   });
 
+  it('handles leading and trailing spaces around styled text without duplicating string', () => {
```
Comment (rickhanlonii) [inline test/draftjsToMd.test.js]: As an example of the bug, this test will fail without these changes

**Comment by kadikraman** [comment]
Looks good to me! I tried to fix this myself, but wasn't able to write a failing test for it. I think I kind of missed what the actual bug was, as I haven't been using `draft.js` for a while.

Thank you for fixing this bug (and the cheeky typo, haha)! 😊

**Comment by rickhanlonii** [comment]
No sweat @kadikraman!

Re: failing test -- did you try the test I added in the PR? Without these changes it should fail with:

**Comment by kadikraman** [comment]
@rickhanlonii Yeah I did try it locally :)
